language: python
python:
  - "3.5"
dist: xenial
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
install:
  - pip install pytest-cov codecov latest_blender_url 
script:
  - cd ForNEURON
  - python setup.py develop
  - cd ..
  - python scripts/install_blender_and_addon.py
  - ./blender/blender --python scripts/install_enable_addon.py --background
  - scripts/install_neuron.sh
  - python tests/test_client.py TestMorphologyExport.test_ping
  - py.test --cov=ForNEURON/blenderneuron tests/test_client.py
after_success:
  - codecov
