language: python
cache:
  directories:
  - $HOME/neuron
python:
  - "3"
install:
  - pip install neuron coverage
  - apt-get install -y libglu1 libxi6 libxrender1
script:
  - cd scripts
  - python install_blender.py
  - export PATH=$PATH:/blender/
  - export PYTHONPATH=/BlenderNEURON
  - export COVERAGE_PROCESS_START=.coveragerc

  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    /blender/2.79/python/bin/python3.5m get-pip.py && \
    rm get-pip.py && \
    /blender/2.79/python/bin/pip install coverage

  - ./link_addon.sh
  - cd ..
  - xvfb-run --auto-servernum --server-args "-screen 0 1920x1080x24" ./test.sh
after_success:
  - coverage
