language: python
python:
  - "3.5"
install:
  - pip install pytest-cov codecov latest_blender_url 
script:
  - cd ForNEURON
  - python setup.py develop
  - cd ..
  - python scripts/install_blender_and_addon.py
  - xvfb-run ./blender/blender --python scripts/install_enable_addon.py --background
  - scripts/install_neuron.sh
  - xvfb-run python tests/test_client.py TestMorphologyExport.test_ping
  - xvfb-run py.test --cov=ForNEURON/blenderneuron tests/test_client.py
after_success:
  - codecov
